library(ggplot2)
library(afex)
library(emmeans)
library(dplyr)
library(car)
library(corrplot)
app.df = read.csv('C:\\R\\apps.csv', header = T)
str(app.df)
table(app.df$app_search)
table(app.df$app_booking)
table(app.df$app_reviews)
table(app.df$app_hostcommunicate)
table(app.df$app_sortfeature)
table(app.df$app_selfcheck)
table(app.df$app_glitch)
table(app.df$app_thirdparty)

corrplot(cor(app.df[,c(9,8:15)]),method = 'ellipse', type = 'upper')
modelapp <- lm(app_booking ~ app_reviews + app_hostcommunicate + app_sortfeature + app_selfcheck + app_glitch + app_thirdparty, data = app.df)
summary (modelapp)

app.aov <- aov(app_booking ~ app_reviews + app_hostcommunicate + app_sortfeature + app_selfcheck + app_glitch + app_thirdparty, data = app.df)
summary(app.aov)