library(ggplot2)
library(afex)
library(emmeans)
library(dplyr)
library(car)
library(corrplot)
price.df = read.csv('C:\\R\\Price.csv', header = T)
str(price.df)
table(price.df$price_base)
table(price.df$price_frequency)
table(price.df$price_superhost)
table(price.df$price_fee)
table(price.df$price_negotiation)
table(price.df$price_hike)
table(price.df$price_bestdeals)

corrplot(cor(price.df[,c(14,9:14)]),method = 'ellipse', type = 'upper')
modelprice <- lm(price_bestdeals ~ price_base + price_frequency + price_superhost + price_fee + price_negotiation + price_hike, data = price.df)
summary (modelprice)

pi.aov <- aov(price_bestdeals ~ price_base + price_frequency + price_superhost + price_fee + price_negotiation + price_hike, data = price.df)
summary(pi.aov)