library(ggplot2)
library(afex)
library(emmeans)
library(dplyr)
library(car)
library(corrplot)
promo.df= read.csv("C:\\R\\msmipromo.csv",header=T)        
str(promo.df)
#What aspects of Airbnb's pricing strategy are responsible for customers possibly booking from a competitor website?
table(promo.df$promo_channel)
table(promo.df$promo_creditcard)
table(promo.df$promo_monthlypromo)
table(promo.df$promo_amenities)
table(promo.df$promo_flexibility)
table(promo.df$promo_rewards)
str(promo.df)
corrplot(cor(promo.df[ , c(5,6:11)]),method='ellipse',type = 'upper')
modelpro<-lm(promo_discount~promo_channel+promo_creditcard+promo_monthlypromo+promo_amenities+promo_flexibility+promo_rewards,data = promo.df)
summary(modelpro)
promo.aov <- aov(promo_discount ~promo_channel+promo_creditcard+promo_monthlypromo+promo_amenities+promo_flexibility+promo_rewards , data = promo.df)
summary(promo.aov)