library(ggplot2)
library(afex)
library(emmeans)
library(dplyr)
library(car)
library(corrplot)
ss.df = read.csv('C:\\R\\Safety and Security.csv', header = T)
str(ss.df)
table(ss.df$ss_security)
table(ss.df$ss_cleanliness)
table(ss.df$ss_protocols)
table(ss.df$ss_scam)
corrplot(cor(ss.df[,c(8,9:11)]),method = 'ellipse', type = 'upper')
modelss <- lm(ss_security ~ ss_protocols + ss_scam + ss_cleanliness, data = ss.df)
summary (modelss)
ss.aov <- aov(ss_security ~ ss_protocols + ss_scam + ss_cleanliness, data = ss.df)
summary(ss.aov)